services:
  frps1:
    image: snowdreamtech/frps
    container_name: frps1
    restart: always
    network_mode: "host"
    volumes:
      - ./frps1.ini:/etc/frp/frps1.toml
    command: ["-c", "/etc/frp/frps1.toml"]
