services:
  wifi-ap:
    build: .
#    network_mode: host
    privileged: true
    environment:
      - AP_IFACE=wlan1
      - AP_IP=192.168.50.1
      - PROFILE=dev
    volumes:
      - ./py:/app
    ports:
      - "81:80"
      - "443:443"
      - "1501:1501"
